"""add stats name

Revision ID: 1032869b932a
Revises: 9feb998c17f5
Create Date: 2020-11-03 14:48:55.100907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1032869b932a'
down_revision = '9feb998c17f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stats_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stats_name')
    # ### end Alembic commands ###
