"""add achievement columns

Revision ID: 1baa44f2391c
Revises: f83002368e34
Create Date: 2022-01-23 19:24:11.997808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1baa44f2391c'
down_revision = 'f83002368e34'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('roulette_attempts', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "roulette_attempts" = 0')
    op.alter_column('user', 'roulette_attempts',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roulette_attempts')
    # ### end Alembic commands ###
