"""add_rewards_earnings

Revision ID: 25a830c68649
Revises: 1baa44f2391c
Create Date: 2022-02-02 15:50:15.455280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a830c68649'
down_revision = '1baa44f2391c'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('rewards_earnings', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "rewards_earnings" = 0')
    op.alter_column('user', 'rewards_earnings',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rewards_earnings')
    # ### end Alembic commands ###
