"""add state

Revision ID: 2c1240b5aa5c
Revises: abc3f2e920b3
Create Date: 2020-07-26 21:23:57.921783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1240b5aa5c'
down_revision = 'abc3f2e920b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'max_bet',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('league', sa.Column('state', sa.String(length=20), nullable=True))
    op.alter_column('league', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('option', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('option', 'odds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'pnkoins',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pnkoins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('option', 'odds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('option', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('league', 'state')
    op.alter_column('category', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'max_bet',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bet', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
