"""add fantasy earnings columns

Revision ID: 440ca2ba486b
Revises: b0d843aa16ff
Create Date: 2020-10-27 21:52:55.142369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440ca2ba486b'
down_revision = 'b0d843aa16ff'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('fantasy_earnings', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "fantasy_earnings" = 0')
    op.alter_column('user', 'fantasy_earnings',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fantasy_earnings')
    # ### end Alembic commands ###
