"""add silver and gold

Revision ID: 48fcb2d13469
Revises: 1032869b932a
Create Date: 2020-12-02 18:48:54.795225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fcb2d13469'
down_revision = '1032869b932a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gold_card', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('silver_card', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'silver_card')
    op.drop_column('user', 'gold_card')
    # ### end Alembic commands ###
