"""add_friendship_state_column

Revision ID: 4e6a1a663800
Revises: 776061ca57c0
Create Date: 2022-02-15 19:44:53.619123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6a1a663800'
down_revision = '776061ca57c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('state', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship', 'state')
    # ### end Alembic commands ###
