"""add cards columns

Revision ID: 69740407ad49
Revises: f1efb5b25a65
Create Date: 2020-10-27 14:40:11.834747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69740407ad49'
down_revision = 'f1efb5b25a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_1_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_2_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_3_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_4_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('card_5_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'card', ['card_1_id'], ['id'])
    op.create_foreign_key(None, 'user', 'card', ['card_5_id'], ['id'])
    op.create_foreign_key(None, 'user', 'card', ['card_3_id'], ['id'])
    op.create_foreign_key(None, 'user', 'card', ['card_2_id'], ['id'])
    op.create_foreign_key(None, 'user', 'card', ['card_4_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'card_5_id')
    op.drop_column('user', 'card_4_id')
    op.drop_column('user', 'card_3_id')
    op.drop_column('user', 'card_2_id')
    op.drop_column('user', 'card_1_id')
    # ### end Alembic commands ###
