"""add fcoins

Revision ID: 6bd7b4b4aabf
Revises: 4bb410f2656f
Create Date: 2022-01-18 20:09:58.125839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd7b4b4aabf'
down_revision = '4bb410f2656f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('fcoins', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "fcoins" = 0')
    op.alter_column('user', 'fcoins',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fcoins')
    # ### end Alembic commands ###
