"""add roulette earnings

Revision ID: b35af0706144
Revises: f17a10cc572d
Create Date: 2020-08-04 17:53:33.793814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35af0706144'
down_revision = 'f17a10cc572d'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('roulette_earnings', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "roulette_earnings" = 0')
    op.alter_column('user', 'earnings',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roulette_earnings')
    # ### end Alembic commands ###
