"""add earnings

Revision ID: c19c42ac0f3c
Revises: 2c1240b5aa5c
Create Date: 2020-07-26 22:00:40.597746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19c42ac0f3c'
down_revision = '2c1240b5aa5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('earnings', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "earnings" = 0')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'pnkoins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'earnings',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pnkoins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'earnings')
    # ### end Alembic commands ###
