"""add reckey

Revision ID: ef026c09a079
Revises: b35af0706144
Create Date: 2020-08-06 18:12:02.776469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef026c09a079'
down_revision = 'b35af0706144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rec_key', sa.String(length=1000), nullable=True))
    op.alter_column('user', 'roulette_earnings',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'roulette_earnings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'rec_key')
    # ### end Alembic commands ###
