"""add credit to league

Revision ID: f17a10cc572d
Revises: 0f0e47487982
Create Date: 2020-07-27 17:44:49.983682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17a10cc572d'
down_revision = '0f0e47487982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('credit', sa.Integer(), nullable=True))
    op.execute('UPDATE "league" SET "credit" = 11000')
    op.alter_column('league', 'credit',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'credit')
    # ### end Alembic commands ###
