"""add cards structure

Revision ID: f1efb5b25a65
Revises: ef026c09a079
Create Date: 2020-10-27 14:38:03.888159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1efb5b25a65'
down_revision = 'ef026c09a079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('old_base_value', sa.Integer(), nullable=True),
    sa.Column('new_base_value', sa.Integer(), nullable=True),
    sa.Column('current_delta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
