"""add achievement columns

Revision ID: f83002368e34
Revises: e13dea44fc6f
Create Date: 2022-01-23 10:56:07.905540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83002368e34'
down_revision = 'e13dea44fc6f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('roulette_streak', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "roulette_streak" = 0')
    op.alter_column('user', 'roulette_streak',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "login_count" = 0')
    op.alter_column('user', 'login_count',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.add_column('user', sa.Column('profile_views', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET "profile_views" = 0')
    op.alter_column('user', 'profile_views',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roulette_streak')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'profile_views')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
